services:
  mailpit:
    image: axllent/mailpit
    container_name: coffee_mailpit
    ports:
      - 1025:1025
      - 8025:8025
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - .:/app
      - deps_cache:/app/deps
      - node_modules_cache:/app/assets/node_modules
    depends_on:
      - db
      - mailpit
    environment:
      - MAILPIT_SMTP_HOST=coffee_mailpit
      - MAILPIT_SMTP_PORT=1025
      - PORT=4004
    # require IEx
    # In the line you want to stop:
    # IEx.pry()
    #
    # docker-compose run --service-ports web
    # Uncomment this line:
    # command: iex -S mix phx.server

    stdin_open: true
    tty: true
  db:
    image: postgres:16
    environment:
      - "POSTGRES_USER=coffee"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data
      - deps_cache:/app/deps
      - node_modules_cache:/app/assets/node_modules
    ports:
      - "5436:5436"

volumes:
  deps_cache:
  node_modules_cache:
